FROM ubuntu:24.04
LABEL MAINTAINER="Pavel Taranov <pavel.a.taranov@gmail.com>"
LABEL DESCRIPTION="Build environment for opentrack"




ARG USER_NAME=nobody
ENV USER=$USER_NAME
ARG UID=2345
ARG GID=2345
ENV OPENTRACK_VERSION=




#To skip setting itimezonei, to set timezone: echo "Australia/Adelaide" | sudo tee /etc/timezone
ENV DEBIAN_FRONTEND=noninteractive




# Basic tools
RUN apt update \
 && apt install -y wget \
                   curl \
                   tree \
                   gawk \
                   zip \
                   lsof \
                   mc \
                   vim \
                   less \
                   git \
                   tig \
                   sudo




# Opentrack dependencies
RUN apt update \
 && apt install -y build-essential \
                   cmake \
                   cmake-curses-gui \
                   gdb \
                   libopencv-dev \
                   libproc2-dev \
                   qtbase5-dev \
                   qttools5-dev \
                   qtbase5-private-dev \
                   xwayland \
                   x11-apps \
                   mesa-utils




# Setup mc \
RUN echo "regex/i/\.(md|log|txt|js|json|ejs|yml|j2|cfg|xml|sql|py|ipynb|sh)$\n    Include=editor" | tee -a /etc/mc/mc.ext.ini




# Create user
# Example: Change UID of 'ubuntu' user to 1001, then create 'myuser' with UID 1000
RUN usermod -u 1234 ubuntu && groupmod -g 1234 ubuntu
RUN groupadd -g $GID $USER
RUN useradd --shell /bin/bash --create-home -u $UID -g $GID $USER
RUN echo "${USER}:${USER}" | chpasswd
RUN usermod -aG sudo $USER
USER $USER
WORKDIR /home/$USER




# Setup vim
RUN echo "set tabstop=4\nset shiftwidth=4\nset softtabstop=4\nset expandtab" | tee -a /home/$USER/.vimrc \
 && echo "export EDITOR=vim" | tee -a /home/$USER/.bashrc




# Copy entrypoint and other scripts
COPY --chown=$USER:$USER\
     files/sysinfo.sh \
     files/build.sh \
     /home/$USER/




#ENTRYPOINT ["/bin/bash"]
ENTRYPOINT ["./build.sh"]
